### ISSUE TITLE
Is this implemention just able to generate sound, or it also support conditional text (TTS)?

### ISSUE THREAD

**Issue by megazone87** [ritheshkumar95/WaveNet#1]
Your example sound like TTS results, but i found none of TTS support.

**Comment by ritheshkumar95** [comment]
For now, only generates sound. I haven't started working on the conditional TTS part yet.

**Comment by virajkarandikar** [comment]
How were the samples generated if TTS part is not yet implemented?

**Comment by ritheshkumar95** [comment]
@virajkarandikar the samples uploaded are really old. I need to take it down. Those were a result of overfitting on a few 1000 audio files from blizzard. 

But my code should work, and it'll produce babbling sound like in the wavenet blog.
