### ISSUE TITLE
Have you changed the src code of theano?

### ISSUE THREAD

**Issue by zoucan520** [ritheshkumar95/WaveNet#2]
In your recipe,I found a non-existent arg(filter_dilation) in src code of theano.
T.nnet.conv2d(input,W,subsample=(1,stride),border_mode=pad,filter_dilation=filter_dilation)

**Comment by ritheshkumar95** [comment]
Hello, 

Thank you for your question.

Have you considered compiling theano from source? I am guessing you have a pip installation of theano which is quite old. 

Theano has included filter dilation in conv2d (https://github.com/Theano/Theano/blob/master/theano/tensor/nnet/abstract_conv.py#L516) for a while now.

Install theano like this:

``
git clone https://github.com/Theano/Theano.git
``
``
cd Theano
``
``
sudo python setup.py install
``

**Comment by zoucan520** [comment]
get it.
thanks for your answer.
I'll try to run your recipe(vctk corpus) .
